package com.jiqu.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ACCOUNT".
 */
public class Account {

    private String nickname;
    private String username;
    private Integer gender;
    private String birthday;
    private String qq;
    private String phone;
    private String level;
    private String email;
    private String uid;
    private String photo;

    public Account() {
    }

    public Account(String uid) {
        this.uid = uid;
    }

    public Account(String nickname, String username, Integer gender, String birthday, String qq, String phone, String level, String email, String uid, String photo) {
        this.nickname = nickname;
        this.username = username;
        this.gender = gender;
        this.birthday = birthday;
        this.qq = qq;
        this.phone = phone;
        this.level = level;
        this.email = email;
        this.uid = uid;
        this.photo = photo;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getQq() {
        return qq;
    }

    public void setQq(String qq) {
        this.qq = qq;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

}
