package com.jiqu.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APPINFO".
 */
public class Appinfo {

    private Short gameName;
    private Integer gameId;
    private Long currentSize;
    private Long gameSize;
    private Integer downloadState;
    private String downloadUrl;
    private String gameIconUrl;
    private String savePath;

    public Appinfo() {
    }

    public Appinfo(Integer gameId) {
        this.gameId = gameId;
    }

    public Appinfo(Short gameName, Integer gameId, Long currentSize, Long gameSize, Integer downloadState, String downloadUrl, String gameIconUrl, String savePath) {
        this.gameName = gameName;
        this.gameId = gameId;
        this.currentSize = currentSize;
        this.gameSize = gameSize;
        this.downloadState = downloadState;
        this.downloadUrl = downloadUrl;
        this.gameIconUrl = gameIconUrl;
        this.savePath = savePath;
    }

    public Short getGameName() {
        return gameName;
    }

    public void setGameName(Short gameName) {
        this.gameName = gameName;
    }

    public Integer getGameId() {
        return gameId;
    }

    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    public Long getCurrentSize() {
        return currentSize;
    }

    public void setCurrentSize(Long currentSize) {
        this.currentSize = currentSize;
    }

    public Long getGameSize() {
        return gameSize;
    }

    public void setGameSize(Long gameSize) {
        this.gameSize = gameSize;
    }

    public Integer getDownloadState() {
        return downloadState;
    }

    public void setDownloadState(Integer downloadState) {
        this.downloadState = downloadState;
    }

    public String getDownloadUrl() {
        return downloadUrl;
    }

    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    public String getGameIconUrl() {
        return gameIconUrl;
    }

    public void setGameIconUrl(String gameIconUrl) {
        this.gameIconUrl = gameIconUrl;
    }

    public String getSavePath() {
        return savePath;
    }

    public void setSavePath(String savePath) {
        this.savePath = savePath;
    }

}
