package com.jiqu.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.jiqu.database.DownloadAppinfo;
import com.jiqu.database.Account;

import com.jiqu.database.DownloadAppinfoDao;
import com.jiqu.database.AccountDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadAppinfoDaoConfig;
    private final DaoConfig accountDaoConfig;

    private final DownloadAppinfoDao downloadAppinfoDao;
    private final AccountDao accountDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadAppinfoDaoConfig = daoConfigMap.get(DownloadAppinfoDao.class).clone();
        downloadAppinfoDaoConfig.initIdentityScope(type);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        downloadAppinfoDao = new DownloadAppinfoDao(downloadAppinfoDaoConfig, this);
        accountDao = new AccountDao(accountDaoConfig, this);

        registerDao(DownloadAppinfo.class, downloadAppinfoDao);
        registerDao(Account.class, accountDao);
    }
    
    public void clear() {
        downloadAppinfoDaoConfig.getIdentityScope().clear();
        accountDaoConfig.getIdentityScope().clear();
    }

    public DownloadAppinfoDao getDownloadAppinfoDao() {
        return downloadAppinfoDao;
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

}
