package com.jiqu.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.jiqu.database.DownloadAppinfo;

import com.jiqu.database.DownloadAppinfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadAppinfoDaoConfig;

    private final DownloadAppinfoDao downloadAppinfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadAppinfoDaoConfig = daoConfigMap.get(DownloadAppinfoDao.class).clone();
        downloadAppinfoDaoConfig.initIdentityScope(type);

        downloadAppinfoDao = new DownloadAppinfoDao(downloadAppinfoDaoConfig, this);

        registerDao(DownloadAppinfo.class, downloadAppinfoDao);
    }
    
    public void clear() {
        downloadAppinfoDaoConfig.getIdentityScope().clear();
    }

    public DownloadAppinfoDao getDownloadAppinfoDao() {
        return downloadAppinfoDao;
    }

}
