package com.jiqu.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DOWNLOAD_APPINFO".
 */
public class DownloadAppinfo {

    /** Not-null value. */
    private String packageName;
    /** Not-null value. */
    private String appName;
    private Long id;
    private Long currentSize;
    /** Not-null value. */
    private String appSize;
    private int downloadState;
    /** Not-null value. */
    private String url;
    private String iconUrl;
    private String apkPath;
    private String zipPath;
    private String unzipPath;
    private Boolean hasFinished;
    private String des;
    private Integer score;
    private Float progress;
    private byte[] iconByte;
    private Boolean isZip;
    private Long thread1;
    private Long thread2;
    private Long thread3;
    private Long thread4;
    private Long thread5;

    public DownloadAppinfo() {
    }

    public DownloadAppinfo(Long id) {
        this.id = id;
    }

    public DownloadAppinfo(String packageName, String appName, Long id, Long currentSize, String appSize, int downloadState, String url, String iconUrl, String apkPath, String zipPath, String unzipPath, Boolean hasFinished, String des, Integer score, Float progress, byte[] iconByte, Boolean isZip, Long thread1, Long thread2, Long thread3, Long thread4, Long thread5) {
        this.packageName = packageName;
        this.appName = appName;
        this.id = id;
        this.currentSize = currentSize;
        this.appSize = appSize;
        this.downloadState = downloadState;
        this.url = url;
        this.iconUrl = iconUrl;
        this.apkPath = apkPath;
        this.zipPath = zipPath;
        this.unzipPath = unzipPath;
        this.hasFinished = hasFinished;
        this.des = des;
        this.score = score;
        this.progress = progress;
        this.iconByte = iconByte;
        this.isZip = isZip;
        this.thread1 = thread1;
        this.thread2 = thread2;
        this.thread3 = thread3;
        this.thread4 = thread4;
        this.thread5 = thread5;
    }

    /** Not-null value. */
    public String getPackageName() {
        return packageName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    /** Not-null value. */
    public String getAppName() {
        return appName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCurrentSize() {
        return currentSize;
    }

    public void setCurrentSize(Long currentSize) {
        this.currentSize = currentSize;
    }

    /** Not-null value. */
    public String getAppSize() {
        return appSize;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppSize(String appSize) {
        this.appSize = appSize;
    }

    public int getDownloadState() {
        return downloadState;
    }

    public void setDownloadState(int downloadState) {
        this.downloadState = downloadState;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public String getApkPath() {
        return apkPath;
    }

    public void setApkPath(String apkPath) {
        this.apkPath = apkPath;
    }

    public String getZipPath() {
        return zipPath;
    }

    public void setZipPath(String zipPath) {
        this.zipPath = zipPath;
    }

    public String getUnzipPath() {
        return unzipPath;
    }

    public void setUnzipPath(String unzipPath) {
        this.unzipPath = unzipPath;
    }

    public Boolean getHasFinished() {
        return hasFinished;
    }

    public void setHasFinished(Boolean hasFinished) {
        this.hasFinished = hasFinished;
    }

    public String getDes() {
        return des;
    }

    public void setDes(String des) {
        this.des = des;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public Float getProgress() {
        return progress;
    }

    public void setProgress(Float progress) {
        this.progress = progress;
    }

    public byte[] getIconByte() {
        return iconByte;
    }

    public void setIconByte(byte[] iconByte) {
        this.iconByte = iconByte;
    }

    public Boolean getIsZip() {
        return isZip;
    }

    public void setIsZip(Boolean isZip) {
        this.isZip = isZip;
    }

    public Long getThread1() {
        return thread1;
    }

    public void setThread1(Long thread1) {
        this.thread1 = thread1;
    }

    public Long getThread2() {
        return thread2;
    }

    public void setThread2(Long thread2) {
        this.thread2 = thread2;
    }

    public Long getThread3() {
        return thread3;
    }

    public void setThread3(Long thread3) {
        this.thread3 = thread3;
    }

    public Long getThread4() {
        return thread4;
    }

    public void setThread4(Long thread4) {
        this.thread4 = thread4;
    }

    public Long getThread5() {
        return thread5;
    }

    public void setThread5(Long thread5) {
        this.thread5 = thread5;
    }

}
