package com.jiqu.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE_TABLE".
 */
public class MessageTable {

    private Long id;
    private String message;

    public MessageTable() {
    }

    public MessageTable(Long id) {
        this.id = id;
    }

    public MessageTable(Long id, String message) {
        this.id = id;
        this.message = message;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

}
